service: fii-staw-fractal
# org: razgraf
# app: fii-staw-fractal

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::serverless-s3-fii-staw-fractal-bucket/*"

functions:
  createFractal:
    handler: handler.createFractal
    layers:
      - arn:aws:lambda:eu-west-2:624340280785:layer:CanvasLib64Layer:2
      - arn:aws:lambda:eu-west-2:624340280785:layer:Node10CanvasLayer:2
    events:
      - http:
          path: fractal
          method: get

  createUser:
    handler: handler.createUser
    layers:
      - arn:aws:lambda:eu-west-2:624340280785:layer:CanvasLib64Layer:2
      - arn:aws:lambda:eu-west-2:624340280785:layer:Node10CanvasLayer:2
    events:
      - http:
          path: user
          method: post

  loginUser:
    handler: handler.loginUser
    layers:
      - arn:aws:lambda:eu-west-2:624340280785:layer:CanvasLib64Layer:2
      - arn:aws:lambda:eu-west-2:624340280785:layer:Node10CanvasLayer:2
    events:
      - http:
          path: user/login
          method: post

  createKey:
    handler: handler.createKey
    layers:
      - arn:aws:lambda:eu-west-2:624340280785:layer:CanvasLib64Layer:2
      - arn:aws:lambda:eu-west-2:624340280785:layer:Node10CanvasLayer:2
    events:
      - http:
          path: user/key
          method: post

resources:
  Resources:
    S3FiiStawFractalBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-s3-fii-staw-fractal-bucket
